const ALL_MEAL_REQUEST = "ALL_MEAL_REQUEST";
const ALL_MEAL_SUCCESS = "ALL_MEAL_SUCCESS";
const ALL_MEAL_FAIL = "ALL_MEAL_FAIL";
const CLEAR_ERRORS = "CLEAR_ERRORS";

export { ALL_MEAL_FAIL, ALL_MEAL_REQUEST, ALL_MEAL_SUCCESS, CLEAR_ERRORS };
