const ALL_MEAL_REQUEST = "ALL_MEAL_REQUEST";
const ALL_MEAL_SUCCESS = "ALL_MEAL_SUCCESS";
const ALL_MEAL_FAIL = "ALL_MEAL_FAIL";
const CLEAR_ERRORS = "CLEAR_ERRORS";

const MEAL_DETAIL_REQUEST = "MEAL_DETAIL_REQUEST";
const MEAL_DETAIL_SUCCESS = "MEAL_DETAIL_SUCCESS";
const MEAL_DETAIL_FAIL = "MEAL_DETAIL_FAIL";
export {
  ALL_MEAL_FAIL,
  ALL_MEAL_REQUEST,
  ALL_MEAL_SUCCESS,
  CLEAR_ERRORS,
  MEAL_DETAIL_REQUEST,
  MEAL_DETAIL_SUCCESS,
  MEAL_DETAIL_FAIL,
};
